---
title: "GQ"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)

options(warn=-1)

load("GQData.Rdata")

library(devtools)
library(kableExtra)
#source_url("https://github.com/CMAP-REPOS/DemographicForecasting/raw/main/GroupQuarters.R")
#source_url("https://github.com/CMAP-REPOS/DemographicForecasting/raw/main/Population.R")
#source_url()
```

## Group Quarters 2010 Summary

```{r, echo = F}
x <- GQ_inst %>%
  filter(Category == 'County Total') %>%
  summarise("Institutionalized" = sum(value))

y <- GQ_noninst %>%
  filter(Category == 'County Total') %>%
  summarise("Non-Institutionalized" = sum(value))

GQ_total <- sum(y+x)
t <- t(cbind(GQ_total,x,y))
colnames(t)[1] <- '2010'
rownames(t)[1] <- 'Group Quarters'

z <- pop_2010 %>%
  filter(Category == 'County Total') %>%
  summarise("2010 Household Population" = sum(value))

t <- rbind(t(z), t)
TOTAL<- GQ_total+sum(z)
t <- rbind(TOTAL, t)

kbl(t, booktabs = T) %>%
  add_indent(c(1), level_of_indent = 1, all_cols = T) %>%
  add_indent(c(2:3), level_of_indent = 2, all_cols = T)
``` 

```{r, echo = F}
x <- GQ_inst %>%
  filter(Category == 'County Total') %>%
  summarise("Institutionalized" = sum(value))

y <- GQ_noninst %>%
  filter(Category == 'County Total') %>%
  summarise("Non-Institutionalized" = sum(value))


m <- as.data.frame(t(cbind(x,y)))


m$percent[1] <- paste(round((x/(sum(x,y))*100),0), "%", sep="")
m$percent[2] <- paste(round((y/(sum(x,y))*100),0), "%", sep="")

m$label[1] <- names(x)
m$label[2] <- names(y)
rownames(m) <- seq(length=nrow(m))

lbls <- paste((m$label), "\n", m$percent, sep="")
pie(m[,1], labels = lbls)

```

## Including Plots

Aggregate example:

```{r pressure, echo=FALSE}
b <- aggregate(GQ_inst$value, by = list(GQ_inst$concept), sum)
GQ$Region <- NA

CMAP <- c("Cook County", "DuPage County", "Kane County", "Kendall County", "Lake County", "McHenry County", "Will County")
OuterCounty <- c("Boone County", "DeKalb County", "Grundy County", "Kankakee County", "LaSalle County", "Lee County", "Ogle County", "Winnebago County")

GQ$Region[GQ$State == ' Wisconsin'] <- 'SE Wisconsin'
GQ$Region[GQ$State == ' Indiana'] <- 'NW Indiana'

GQ$Region[GQ$County %in% CMAP & GQ$State == " Illinois"] <- "CMAP"
GQ$Region[GQ$County %in% OuterCounty & GQ$State == " Illinois"] <- "IL Outer County"

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
